name: Health Check

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check backend health
      id: health
      run: |
        STATUS="DOWN"
        CUSTOM_MESSAGE="The backend server is currently down. Please try again later."
        IMAGE="<img alt="status" title="Status" src="https://custom-icon-badges.demolab.com/badge/-server status: offline-aa0000?style=for-the-badge&logo=server&logoColor=white%22"/></a>"
        if curl -s https://harmless-ram-luckily.ngrok-free.app/health | grep -q 'UP'; then
          STATUS="UP"
          CUSTOM_MESSAGE="The backend server is up and running smoothly."
          IMAGE="<img alt="status" title="Status" src="https://custom-icon-badges.demolab.com/badge/-server status: online-00aa00?style=for-the-badge&logo=server&logoColor=white%22"/></a>"
        fi
        echo "::set-output name=status::$STATUS"
        echo "::set-output name=message::$CUSTOM_MESSAGE"
        echo "::set-output name=image::$IMAGE"

    - name: Update README with status
      run: |
        IMAGE=${{ steps.health.outputs.image }}
        sed -i '/<!-- health-status -->/c\'"$IMAGE"'' README.md

    - name: Commit and push status update
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update health status to ${{ steps.health.outputs.message }}"
        git push
